# Generated by Django 3.2.3 on 2021-05-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carona',
        ),
    ]
