# Generated by Django 3.2.2 on 2021-05-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
    ]
